### ISSUE TITLE
rest/scenario-4 is json but it traverse through text/plain

### ISSUE THREAD

**Issue by silveoj** [Romakita/tsed-issue-1222#1]
https://github.com/TypedProject/tsed/issues/1222

Hello @Romakita 
rest/scenario-4 returns me `{"filter":{"jsonexample":1}}` but it's JSON, not text/plain.
I expect `{"jsonexample":1}`.

If you add second filter `@ResponseFilter("*/*")` it will be called instead of `text/plain`.

**Comment by Romakita** [comment]
well, all unit tests works and the ci confirm it.
You have the right access on this repo, so Update the repository with you scenario please :)

**Comment by silveoj** [comment]
I update repository but I used your scenarion-4. Just I do it locally, in Postman.

Permission denied.

**Comment by Romakita** [comment]
1) i sent you a github invitation. Look on your mail ;)
2) run test is important to understand your expectation and confirm the problem. The test is the same thing as run a postman and to easy to share it. It just to help me. I had lot a stuff this week so more reproducible info I have more I’ll be fast to fix the problem.

**Comment by Romakita** [comment]
I don’t understand why the scenario-4 must be a plain/text for you. The returned object is an object, so the response will be automatically returned as a json. This is the normal behavior. 
I probably miss something...

**Comment by silveoj** [comment]
Sorry but I don't have any emails))
I updated my fork with postman collection.

Maybe I don't understand why we use Filter.
I suggest:
1. send `rest/scenario-4`. I don't use `setHeader` or swagger.
2. we have 1 filters (text/plain). But I send no `plain/text`. It's plain JS object. So it will `application/json`. Right?
3. Filter is called for scenarion-4. I suggest it's not correctly because it's json. Right?
4. Postman gets `{"filter":{"jsonexample":1}}` and `Content-Type` header as `text/plain; charset=utf-8`. But I suggest it must be `{"jsonexample":1}` and `*/*; charset=utf-8` or `application/json; charset=utf-8`.

I do not hurry. I don't use filters in real projects. Can be discussed endlessly.

**Comment by silveoj** [comment]
Sorry but I don't have any emails))
I updated my fork with postman collection.

Maybe I don't understand why we use Filter.
I suggest:
1. send `rest/scenario-4`. I don't use `setHeader` or swagger.
2. we have 1 filters (text/plain). But I send no `plain/text`. It's plain JS object. So it will `application/json`. Right?
3. Filter is called for scenario-4. I suggest it's not correctly because it's json. Right or not?
4. Postman gets `{"filter":{"jsonexample":1}}` and `Content-Type` header as `text/plain; charset=utf-8`. But I suggest it must be `{"jsonexample":1}` and `*/*; charset=utf-8` or `application/json; charset=utf-8`.

I do not hurry. I don't use filters in real projects. Can be discussed endlessly.

**Comment by silveoj** [comment]
Sorry but I don't have any emails))
I updated my fork with postman collection.

Maybe I don't understand how we use Filter.
I suggest:
1. send `rest/scenario-4`. I don't use `setHeader` or swagger.
2. we have 1 filters (text/plain). But I send no `plain/text`. It's plain JS object. So it will `application/json`. Right?
3. Filter is called for scenario-4. I suggest it's not correctly because it's json. Right or not?
4. Postman gets `{"filter":{"jsonexample":1}}` and `Content-Type` header as `text/plain; charset=utf-8`. But I suggest it must be `{"jsonexample":1}` and `*/*; charset=utf-8` or `application/json; charset=utf-8`.

I don't hurry. I don't use filters in real projects. Can be discussed endlessly.

**Comment by Romakita** [comment]
> Sorry but I don't have any emails))
You have an email associated to your github account (it's mandatory). So the invitation is sent to this email ;)

@silveoj Why don't you send me the postman (or curl) for each point? Can't send me your collection please (https://learning.postman.com/docs/collaborating-in-postman/sharing/#sharing-by-link)

I see the code filter is wrong. The error is to return an object in the transform function. This is why we have a json type.

```typescript
@ResponseFilter("text/plain") // text/plain for example.
export class TextPlainFilter implements ResponseFilterMethods {
  transform(data: any) {
    return {
      filter: data /// wrong
    };
  }
}
```
The correct implementation should be:

```typescript
@ResponseFilter("text/plain") // text/plain for example.
export class TextPlainFilter implements ResponseFilterMethods {
  transform(data: any) {
    return JSON.stringify({
      filter: data /// wrong
    });
  }
}
```
I'll update this repository with you new information.

**Comment by Romakita** [comment]
> send `rest/scenario-4`. I don't use `setHeader` or swagger. 

Returns decorator isn't only for swagger. Ts.ED in v6 use the stored metadata with the `@Returns`.
By default, if the contentType is missing in metadata, Ts.ED will use the  `express.response.json()` method if the data is an object. (e.g. scenario-4). The TextPlainFilter won't be called (unit test confirm this point).

```typescript
    const response = await request.get("/rest/scenario-4").expect(200);

    expect(response.headers["content-type"]).toEqual("application/json; charset=utf-8");
    expect(textPlainFilter.transform).not.toBeCalled(); // HERE NOT CALLED!!!
    expect(response.body).toEqual({
      jsonexample: 1
    });
```
> So I don't know how you can confirm that the filter is called!! Give me a curl which demonstrates the opposite case.

So if you set the content-type with `@Returns(200, String).ContentType('text/plain')`, Ts.ED will forward the content-type to Express `response.contentType('plain/text')`.  But the result depend on how the framework (Express/koa) handle the content-type (fix v6.24.1).

- Express.js: Will transform the object to a string.
- Koa.js: Will change the content-type to application/json automatically.

So, the correct usage when you want a `text/plain` content-type, is to return the data as String from the filter!

The repository is up-to-date with a new scenario (e.g.: scenario-7).

I think the implementation (TextPlainFilter) filter isn't correct in our repository!
See you
Romain

**Comment by silveoj** [comment]
https://www.getpostman.com/collections/cee7a147010b0a348b14

```
  @Get("/scenario-8")
  public scenario8() {
    return {
      jsonexample: 1
    };
  }
```
```
@ResponseFilter("text/plain") // text/plain for example.
export class MyResponseFilter implements ResponseFilterMethods {
  transform() {
    console.log("ResponseFilter: text/plain");
    return "plain text";
  }
}
```

in scenario-8 I get `plain text`.
So if I got it (I didn't)) ):
framework (express/koa/...) will return `{ jsonexample: 1 }` object. ContentType is missing in metadata so `express.response.json()` will be called. But framework decides it's text/plain. So @tsed calls `MyResponseFilter`. And Postman show me `plain text` and `text/plain; charset=utf-8` content-type.

**Comment by Romakita** [comment]
Based on your example and your postman (Ts.ED v6.24.1):

What is certain is that the filter is never called:
<img width="943" alt="Capture d’écran 2021-02-04 à 08 51 17" src="https://user-images.githubusercontent.com/1763311/106861608-46a97300-66c6-11eb-9b51-fd99153a011c.png">

But the unit test give a different result from the postman collection.

Here a list of screens:
screen1:
<img width="1291" alt="Capture d’écran 2021-02-04 à 08 46 48" src="https://user-images.githubusercontent.com/1763311/106861685-5f198d80-66c6-11eb-9ba8-f3e247cad511.png">

screen2:
<img width="1439" alt="Capture d’écran 2021-02-04 à 08 45 12" src="https://user-images.githubusercontent.com/1763311/106861960-bf103400-66c6-11eb-98b9-4cf95b8bc1d7.png">

screen3:
<img width="1439" alt="Capture d’écran 2021-02-04 à 09 00 38" src="https://user-images.githubusercontent.com/1763311/106862488-7e64ea80-66c7-11eb-9fc7-331c56fc7392.png">

Analyse:

- In the screen 1, we can see that the filter isn't called, the content-type is application/json
- In the postman screenshot 3, the content-type is */* (screen 3). I agree, it's not normal.
- For the twice screenshots the result is a json (screen 2), not the `plain-text`. (eg: `Postman show me plain text and text/plain; charset=utf-8 content-type`).

For the difference between postman and the unit test, I reproduced the issue (hence the importance of having your postman collection! We could have saved time from the start ;)) by adding the same headers sent by default by postman:

<img width="1542" alt="Capture d’écran 2021-02-04 à 09 13 56" src="https://user-images.githubusercontent.com/1763311/106863814-570f1d00-66c9-11eb-9ed8-2827012822c8.png">

Headers sent by postman:
<img width="1440" alt="Capture d’écran 2021-02-04 à 09 12 58" src="https://user-images.githubusercontent.com/1763311/106863867-69895680-66c9-11eb-8565-ae13c08cd138.png">

So to fix the postman, I changed the Accept header to "application/json".

<img width="1440" alt="Capture d’écran 2021-02-04 à 09 23 07" src="https://user-images.githubusercontent.com/1763311/106864813-a73aaf00-66ca-11eb-9375-fd5b16ee6563.png">

```js
pm.test("Content-Type is application/json", function () {
    pm.response.to.have.header("Content-Type", "application/json; charset=utf-8");
});
```

Now, the postman test works. I agree, this point isn't clear for me, but filters isn't the problem, because the TextPlainFilter isn't never called for the scenario8. You can checkout the branch `add-scenario-8`, run `yarn install` and get the my updated postman https://www.getpostman.com/collections/2fd9b768a6134cc3a91b and confirm it.

Based on the analyses, I added the same reproducible scenario on Ts.ED :
<img width="1254" alt="Capture d’écran 2021-02-04 à 09 38 01" src="https://user-images.githubusercontent.com/1763311/106866612-f5e94880-66cc-11eb-876e-d85a69e73267.png">

And I found the offending code fairly quickly:
<img width="675" alt="Capture d’écran 2021-02-04 à 09 36 46" src="https://user-images.githubusercontent.com/1763311/106866408-b3277080-66cc-11eb-8cbc-29a22607f526.png">

Because accept header is */*, the framework set the same content type for the response. I don't think that's what we want in this scenario. The best would be to filter this content-type to let Express / Koa decide on the best content-type to apply.

The fix:
```typescript
      if (bestContentType) {
        return [].concat(bestContentType as any).filter((type) => type !== "*/*")[0];
      }
```

The PR: https://github.com/TypedProject/tsed/pull/1230

Conclusion:
- Use `@Returns` decorator would have avoided having this result since the right content type would have been predefined for the endpoint.
- The postman allowed me to quickly find the problem. In the future, I should always request a curl / postman before agreeing to investigate an issue like this.
- The filter works as expected if you install the v6.24.1 (at least).
 
See you
Romain :)
